version: "3.7"
services:
  mongo:
    image: mongo:4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kemenudb
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js