spring.profiles: dev

server:
  port: 8085
  address: 127.0.0.1

app:
  version: @project.version@
  secret: secret
  refresh: refresh
  recaptcha:
    public: 6LdTMfUUAAAAANcZwb0O_jEXYMElMEAyYdHmnKeM
    secret: ${RECAPTCHA_TOKEN}
  cors: http://localhost:8085, http://localhost:4200
  admin:
    username: admin@example.com
    password: admin
  sendgrid: ${KEMENU_REGISTER_EMAILS}

spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/kemenudb
---
spring.profiles: prod

server:
  port: 8085
  address: 127.0.0.1

app:
  version: @project.version@
  secret: ${JWT_SECRET}
  refresh: ${JWT_SECRET_REFRESH}
  recaptcha:
    public: 6LdTMfUUAAAAANcZwb0O_jEXYMElMEAyYdHmnKeM
    secret: ${RECAPTCHA_TOKEN}
  cors: https://kemenu.com, https://www.kemenu.com
  admin:
    username: admin@kemenu.com
    password: ${KEMENU_ADMIN_PWD}
  sendgrid: ${KEMENU_REGISTER_EMAILS}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER_KEMENU}:${MONGO_DB_PWD_KEMENU}@localhost:27017/${MONGO_DB_NAME_KEMENU}