spring.profiles: dev

server:
  port: 8085
  address: 127.0.0.1
  tomcat:
    mbeanregistry:
      enabled: true

app:
  version: @project.version@
  secret: secret
  refresh: refresh
  recaptcha:
    public: 6LdTMfUUAAAAANcZwb0O_jEXYMElMEAyYdHmnKeM
    secret: ${RECAPTCHA_TOKEN}
  cors: http://localhost:8085, http://localhost:4200
  admin:
    username: admin@example.com
    password: adminPassword
  sendgrid: ${KEMENU_REGISTER_EMAILS}
  cloudinary:
    key: ${CLOUDINARY_KEY}
    secret: ${CLOUDINARY_SECRET}
    cloudname: ${CLOUDINARY_CLOUDNAME}

spring:
  jmx:
    enabled: true
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27018/kemenudb
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB
---
spring.profiles: prod

server:
  port: 8085
  address: 127.0.0.1
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: "*"
  metrics:
    export:
      datadog:
        api-key: ${DD_API_KEY}

app:
  version: @project.version@
  secret: ${JWT_SECRET}
  refresh: ${JWT_SECRET_REFRESH}
  recaptcha:
    public: 6LdTMfUUAAAAANcZwb0O_jEXYMElMEAyYdHmnKeM
    secret: ${RECAPTCHA_TOKEN}
  cors: https://kemenu.com, https://www.kemenu.com
  admin:
    username: admin@kemenu.com
    password: ${KEMENU_ADMIN_PWD}
  sendgrid: ${KEMENU_REGISTER_EMAILS}
  cloudinary:
    key: ${CLOUDINARY_KEY}
    secret: ${CLOUDINARY_SECRET}
    cloudname: ${CLOUDINARY_CLOUDNAME}

spring:
  jmx:
    enabled: true
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER_KEMENU}:${MONGO_DB_PWD_KEMENU}@localhost:27017/${MONGO_DB_NAME_KEMENU}?replicaSet=k3m
  servlet:
    multipart:
      max-file-size: 18MB
      max-request-size: 18MB