name: Kemenu CI

on: [push]

jobs:

  kemenu_testing:
    name: Kemenu testing job
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/rollback' && github.ref != 'refs/heads/redeploy'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Lint & Test frontend
        run: |
          npm install kemenu-frontend --prefix ./kemenu-frontend
          npm --prefix kemenu-frontend run lint
          npm --prefix kemenu-frontend run test
          npm --prefix kemenu-frontend run build
      - name: Test backend
        run: mvn -B clean test package -pl :kemenu-backend
      - name: Run backend
        run: |
          APP_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          export RECAPTCHA_TOKEN=${{ secrets.RECAPTCHA_TOKEN }} && export KEMENU_REGISTER_EMAILS=${{ secrets.KEMENU_REGISTER_EMAILS }} && export CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} && export CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} && export CLOUDINARY_CLOUDNAME=${{ secrets.CLOUDINARY_CLOUDNAME }} && java -Dspring.profiles.active=dev -jar ${{ github.workspace }}/kemenu-backend/target/kemenu-backend-$APP_RELEASE_VERSION.jar &
      - name: Run acceptance tests
        run: mvn -B clean test -pl :kemenu-acceptance-tests

  kemenu_deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: kemenu_testing
    if: github.ref == 'refs/heads/master'
    env:
      KILL_JAVA_SH: ${{ github.workspace }}/ci/kill_java_process.sh
      JAVA_CMD_PATH: ~/jdk/bin/java
      JAR_NAME: kemenu-backend-
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Set up Node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Build frontend
        run: |
          npm install kemenu-frontend --prefix ./kemenu-frontend
          npm --prefix kemenu-frontend run build -- --prod
      - name: Create version
        run: |
          APP_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          APP_RELEASE_VERSION=${APP_RELEASE_VERSION%"-SNAPSHOT"}
          APP_RELEASE_VERSION_ARRAY=(${APP_RELEASE_VERSION//./ })
          APP_RELEASE_VERSION_MINOR=APP_RELEASE_VERSION_ARRAY[2]
          APP_RELEASE_VERSION_MINOR=$((APP_RELEASE_VERSION_MINOR + 1))
          APP_RELEASE_VERSION="${APP_RELEASE_VERSION_ARRAY[0]}.${APP_RELEASE_VERSION_ARRAY[1]}.${APP_RELEASE_VERSION_MINOR}"
          echo "JAR_NAME=$JAR_NAME$APP_RELEASE_VERSION-SNAPSHOT.jar" >> $GITHUB_ENV
          echo "RELEASE VERSION: ${APP_RELEASE_VERSION}-SNAPSHOT"
          mvn -B --batch-mode release:update-versions -DdevelopmentVersion=$APP_RELEASE_VERSION-SNAPSHOT
      - name: Cache maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build backend
        run: mvn -B clean package -Dmaven.test.skip=true -pl :kemenu-backend
      - name: Prepare SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_CLIENT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_PUB_KEY }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Kill java process
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' < $KILL_JAVA_SH
      - name: Moving old jar
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "mv kemenu-backend-*.jar ~/old_jars/"
      - name: Copy jar to server
        run: |
          scp -P ${{ secrets.PORT }} ${{ github.workspace }}/kemenu-backend/target/$JAR_NAME ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~
      - name: Launch app
        run: |
          ssh -f -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "export MONGO_DB_USER_KEMENU=${{ secrets.MONGO_DB_USER_KEMENU }} && export MONGO_DB_PWD_KEMENU=${{ secrets.MONGO_DB_PWD_KEMENU }} && export MONGO_DB_NAME_KEMENU=${{ secrets.MONGO_DB_NAME_KEMENU }} && export JWT_SECRET=${{ secrets.JWT_SECRET }} && export JWT_SECRET_REFRESH=${{ secrets.JWT_SECRET_REFRESH }} && export RECAPTCHA_TOKEN=${{ secrets.RECAPTCHA_TOKEN }} && export KEMENU_ADMIN_PWD=${{ secrets.KEMENU_ADMIN_PWD }} && export KEMENU_REGISTER_EMAILS=${{ secrets.KEMENU_REGISTER_EMAILS }} && export CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} && export CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} && export CLOUDINARY_CLOUDNAME=${{ secrets.CLOUDINARY_CLOUDNAME }} && export DD_API_KEY=${{ secrets.DD_API_KEY }} && $JAVA_CMD_PATH -Dsentry.dsn=${{ secrets.SENTRY_DSN }} -Dspring.profiles.active=prod -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.1.1 -Xms256M -Xmx2G -jar $JAR_NAME &"
      - name: Commit version
        run: |
          git config --global user.name 'Nicolas Vargas Ortega'
          git config --global user.email 'soasada@users.noreply.github.com'
          git pull
          git commit -am "CI/CD: $JAR_NAME artifact deployed"
          git push

  deploy_previous:
    name: Deploy Previous Version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/rollback'
    env:
      KILL_JAVA_SH: ${{ github.workspace }}/ci/kill_java_process.sh
      JAVA_CMD_PATH: ~/jdk/bin/java
      JAR_NAME: kemenu-backend-
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Create version
        run: |
          APP_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          APP_RELEASE_VERSION=${APP_RELEASE_VERSION%"-SNAPSHOT"}
          APP_RELEASE_VERSION_ARRAY=(${APP_RELEASE_VERSION//./ })
          APP_RELEASE_VERSION_MINOR=APP_RELEASE_VERSION_ARRAY[2]
          APP_RELEASE_VERSION_MINOR=$((APP_RELEASE_VERSION_MINOR - 1))
          APP_RELEASE_VERSION="${APP_RELEASE_VERSION_ARRAY[0]}.${APP_RELEASE_VERSION_ARRAY[1]}.${APP_RELEASE_VERSION_MINOR}"
          echo "JAR_NAME=$JAR_NAME$APP_RELEASE_VERSION-SNAPSHOT.jar" >> $GITHUB_ENV
          echo $JAR_NAME
      - name: Prepare SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_CLIENT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_PUB_KEY }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Kill java process
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' < $KILL_JAVA_SH
      - name: Launch app
        run: |
          ssh -f -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "export MONGO_DB_USER_KEMENU=${{ secrets.MONGO_DB_USER_KEMENU }} && export MONGO_DB_PWD_KEMENU=${{ secrets.MONGO_DB_PWD_KEMENU }} && export MONGO_DB_NAME_KEMENU=${{ secrets.MONGO_DB_NAME_KEMENU }} && export JWT_SECRET=${{ secrets.JWT_SECRET }} && export JWT_SECRET_REFRESH=${{ secrets.JWT_SECRET_REFRESH }} && export RECAPTCHA_TOKEN=${{ secrets.RECAPTCHA_TOKEN }} && export KEMENU_ADMIN_PWD=${{ secrets.KEMENU_ADMIN_PWD }} && export KEMENU_REGISTER_EMAILS=${{ secrets.KEMENU_REGISTER_EMAILS }} && export CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} && export CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} && export CLOUDINARY_CLOUDNAME=${{ secrets.CLOUDINARY_CLOUDNAME }} && export DD_API_KEY=${{ secrets.DD_API_KEY }} && $JAVA_CMD_PATH -Dsentry.dsn=${{ secrets.SENTRY_DSN }} -Dspring.profiles.active=prod -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.1.1 -Xms256M -Xmx2G -jar ~/old_jars/$JAR_NAME &"

  deploy_current:
    name: Deploy Current Version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/redeploy'
    env:
      KILL_JAVA_SH: ${{ github.workspace }}/ci/kill_java_process.sh
      JAVA_CMD_PATH: ~/jdk/bin/java
      JAR_NAME: kemenu-backend-
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Create version
        run: |
          APP_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "JAR_NAME=$JAR_NAME$APP_RELEASE_VERSION.jar" >> $GITHUB_ENV
      - name: Prepare SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_CLIENT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_PUB_KEY }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Kill java process
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' < $KILL_JAVA_SH
      - name: Launch app
        run: |
          ssh -f -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "export MONGO_DB_USER_KEMENU=${{ secrets.MONGO_DB_USER_KEMENU }} && export MONGO_DB_PWD_KEMENU=${{ secrets.MONGO_DB_PWD_KEMENU }} && export MONGO_DB_NAME_KEMENU=${{ secrets.MONGO_DB_NAME_KEMENU }} && export JWT_SECRET=${{ secrets.JWT_SECRET }} && export JWT_SECRET_REFRESH=${{ secrets.JWT_SECRET_REFRESH }} && export RECAPTCHA_TOKEN=${{ secrets.RECAPTCHA_TOKEN }} && export KEMENU_ADMIN_PWD=${{ secrets.KEMENU_ADMIN_PWD }} && export KEMENU_REGISTER_EMAILS=${{ secrets.KEMENU_REGISTER_EMAILS }} && export CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} && export CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} && export CLOUDINARY_CLOUDNAME=${{ secrets.CLOUDINARY_CLOUDNAME }} && export DD_API_KEY=${{ secrets.DD_API_KEY }} && $JAVA_CMD_PATH -Dsentry.dsn=${{ secrets.SENTRY_DSN }} -Dspring.profiles.active=prod -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.1.1 -Xms256M -Xmx2G -jar $JAR_NAME &"
